/*
 * This file is generated by jOOQ.
 */
package cy.jooq;


import cy.jooq.tables.UserInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bbm_hospital
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bbm_hospital.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
