/*
 * This file is generated by jOOQ.
 */
package cy.jooq.tables.records;


import cy.jooq.tables.UserInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record5<String, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = -321342140;

    /**
     * Setter for <code>bbm_hospital.user_info.id</code>. User ID
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bbm_hospital.user_info.id</code>. User ID
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bbm_hospital.user_info.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bbm_hospital.user_info.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bbm_hospital.user_info.left_time</code>.
     */
    public void setLeftTime(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bbm_hospital.user_info.left_time</code>.
     */
    public Integer getLeftTime() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bbm_hospital.user_info.last_use_time</code>.
     */
    public void setLastUseTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>bbm_hospital.user_info.last_use_time</code>.
     */
    public Timestamp getLastUseTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>bbm_hospital.user_info.bind_qq</code>.
     */
    public void setBindQq(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bbm_hospital.user_info.bind_qq</code>.
     */
    public String getBindQq() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, Integer, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, Integer, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserInfo.USER_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return UserInfo.USER_INFO.USERNAME;
    }

    @Override
    public Field<Integer> field3() {
        return UserInfo.USER_INFO.LEFT_TIME;
    }

    @Override
    public Field<Timestamp> field4() {
        return UserInfo.USER_INFO.LAST_USE_TIME;
    }

    @Override
    public Field<String> field5() {
        return UserInfo.USER_INFO.BIND_QQ;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public Integer component3() {
        return getLeftTime();
    }

    @Override
    public Timestamp component4() {
        return getLastUseTime();
    }

    @Override
    public String component5() {
        return getBindQq();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public Integer value3() {
        return getLeftTime();
    }

    @Override
    public Timestamp value4() {
        return getLastUseTime();
    }

    @Override
    public String value5() {
        return getBindQq();
    }

    @Override
    public UserInfoRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public UserInfoRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserInfoRecord value3(Integer value) {
        setLeftTime(value);
        return this;
    }

    @Override
    public UserInfoRecord value4(Timestamp value) {
        setLastUseTime(value);
        return this;
    }

    @Override
    public UserInfoRecord value5(String value) {
        setBindQq(value);
        return this;
    }

    @Override
    public UserInfoRecord values(String value1, String value2, Integer value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(String id, String username, Integer leftTime, Timestamp lastUseTime, String bindQq) {
        super(UserInfo.USER_INFO);

        set(0, id);
        set(1, username);
        set(2, leftTime);
        set(3, lastUseTime);
        set(4, bindQq);
    }
}
